### ISSUE TITLE
Necessity of BioC XML format

### ISSUE THREAD

**Issue by duncster94** [ncbi/GNorm2#6]
Hi, thanks for providing this tool!

I plan to run GNorm2 on a set of full-text papers I have acquired. These papers are provided as unstructured full-text - not in BioC XML format. My plan is to simply copy the full-text into the `<text></text>` tags of a minimal BioC XML template, like this:
\
![bat064f3p](https://github.com/ncbi/GNorm2/assets/25830706/ec2c3438-9a2d-4b07-aab8-51b93a8d9580)
\
Is this appropriate for performant NER/normalization? Is GNorm2 conditioned on certain semantic elements (e.g. section headers like "Abstract", "Intro", "Methods", etc.) or does this not matter for performance?

Thanks!

**Comment by rezartadogan** [comment]
Hi Duncan, 

GNorm2 accepts both BioC XML, and PubTator formats, and you can use either one. 
This page (https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/Format.html) lists examples.  

Your example above is valid BioC XML and it should be fine. GNorm2 does not depend on section header elements to make a prediction about a gene name, so even if you have all passages as type "paragraph" it would not be an issue. 

Having said that, if you want, it is possible that you may retrieve the BioC version of your papers  if they are part of these collections: 

Complete Open Access Subset: ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_file_list.txt
Commercial Use Collection: ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_comm_use_file_list.txt
PMC Author Manuscript Collection: ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/manuscript/filelist.txt

IF so, you can use the FTP site to download the BioC format of your files. Or you can retrieve them via the API.

**Comment by duncster94** [comment]
Hi, thanks for the quick response! This works nicely for my purposes. In terms of the paper set: I'm in the process of acquiring non-OA full-text papers from various journals via their text and data-mining APIs via my institutional license. Unfortunately these papers are not provided in a standardized format so the easiest option will be to convert all of them to unstructured plain text, insert into a BioC XML template, and pass this through GNorm2.

Thanks again for your help!
